#!/bin/bash

set -ex

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin

cd ${GOPATH}/src/github.com/starkandwayne.com/shield

set -ex
pwd
go env

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega

godep restore
make

# vim:ft=bash
